language: node_js
node_js:
  - "9"

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli
   - npm install --save @angular/material @angular/cdk
   - npm install --save @angular/animations

script:
   - ng build --prod
