language: node_js
node_js:
  - "9"

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli
   - npm install --save @angular/material @angular/cdk
   - npm install --save @angular/animations

script:
   - ng build --prod


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $showmethereturn  # Set in travis-ci.org dashboard, marked secure
  keep-history: true

  on:
    branch: master

  local-dir: dist
