language: node_js
node_js:
  - "iojs"
  - "7"

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli
   - npm install --save @angular/material @angular/cd
   - npm install --save @angular/animations

script:
   - ng build --prod --aot
