pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
             
                sh 'docker build -t showmethereturn .'

              dir('kubernetes')  {
                sh 'kubectl apply -f showmethereturn.yaml'
              }

            }
        }

    }
}
