pipeline {
    agent any
    stages {
        stage('Build') {
            steps {

                sh 'docker build -t showmethereturn:v1 .'

              dir('kubernetes')  {
                sh 'kubectl create -f showmethereturn.yaml'
              }

            }
        }

    }
}
